many changes, almost done

diff --git a/roles/autobrains_update/templates/autobrains_update.sh.j2 b/roles/autobrains_update/templates/autobrains_update.sh.j2
--- a/roles/autobrains_update/templates/autobrains_update.sh.j2
+++ b/roles/autobrains_update/templates/autobrains_update.sh.j2
@@ -318,6 +318,37 @@ done
 
 }
 
+function uploaded_cert_bundle_diff_loop {
+  ATS_DIR="{{autobrains_config["deflect_dir"]}}/edges/$DNET{{autobrains_config["trafficserver_dir"]}}"
+  for i in {{tls_upload_output}}$DNET/*; do
+    ls $i > /dev/null 2>&1 
+    RT=$?
+    if [ "$RT" -gt 0 ]; then 
+      continue
+    fi   
+    local test=$(match_bypass_file "$(basename $i)")
+    if [ $test -gt 0 ]; then 
+      echo -e "Bypassing file $(basename $i)" 
+      continue
+    fi   
+    DIFF_FILES="$ATS_DIR/conf/ssl/$(basename $i) $i"
+    diff -Nq $DIFF_FILES
+    RT=$?
+    if [ $RT -eq 2 ]
+    then 
+      echo "ERROR: There was something wrong with the diff command"
+    elif [ $RT -eq 1 ]
+    then 
+      yorn "Do you want to install this file in $DNET" "install_file $i $ATS_DIR/conf/ssl/$(basename $i)" 
+      [ "$yn" = 'n' ] || [ "$yn" = 'N' ] && SKIPPED_INSTALL[$DNET]=0 || REMAP_TOUCHED[$DNET]=0
+      echo -e $ECHO_SEPARATOR 
+    fi   
+  fi
+    
+done
+
+}
+
 function banjax_diff_loop {
   ATS_DIR="{{autobrains_config["deflect_dir"]}}/edges/$DNET{{autobrains_config["trafficserver_dir"]}}"
   for i in {{banjax_output}}$DNET/banjax.d/*.bconf; do
@@ -537,6 +568,7 @@ for DNET in $DNETS; do
   cache_diff
   zone_diff_loop
   le_cert_bundle_diff_loop
+  uploaded_cert_bundle_diff_loop
   dashboard_timestamp_diff
 done
   bind_local_templated_diff
@@ -604,7 +636,7 @@ function controller_update() {
   # Check to make sure override.yml does not have sites not in clients.yml
   check_override
 
-  rm -rf {{ats_output}} {{banjax_output}} {{bind_output}} 
+  rm -rf {{ats_output}} {{banjax_output}} {{bind_output}} {{tls_upload_output}}
   if [ -n "$DEBUG" ]; then
     ansible-playbook {{playbook_dir}}/site.yml -l controller
     local exitcode=$?
@@ -838,7 +870,7 @@ function letsencrypt_update() {
 
 function sync_dashboard_tls() {
   # get files uploaded manually to dashboard
-  rsync -e "ssh -p {{autobrains_config["dashadmin_ssh_port"]}}" {{autobrains_config["dashadmin_host"]}}:/{{autobrains_config["tls_bundles_path"]}} config/tls_bundles
+  rsync -e "ssh -p {{autobrains_config["dashadmin_ssh_port"]}}" {{autobrains_config["dashadmin_host"]}}:/{{autobrains_config["tls_bundles_path"]}} {{tls_home}}/encrypted
 }
 
 #########
