add override.yml validation against clients.yml

diff --git a/roles/autobrains_update/templates/autobrains_update.sh.j2 b/roles/autobrains_update/templates/autobrains_update.sh.j2
--- a/roles/autobrains_update/templates/autobrains_update.sh.j2
+++ b/roles/autobrains_update/templates/autobrains_update.sh.j2
@@ -3,6 +3,7 @@
 # {{no_edit_template}}
 # {{no_edit_template}}
 # {{no_edit_template}}
+# ./autobrains_update.sh -i --force will update this file from template
 # {{no_edit_template}}
 # {{no_edit_template}}
 # {{no_edit_template}}
@@ -52,6 +53,7 @@ DEBUG=false
 NOSPIN=false
 NOCLIENT=false
 INITAU=false
+OVERRIDECHECKED=false
 
 if [ -n "$SUDO_USER" ] ; then
   UNAME=$SUDO_USER ; else
@@ -501,6 +503,10 @@ function cat_blacklist() {
 }
 
 function controller_update() {
+  # Check to make sure override.tml does not have sites not in clients.yml
+  check_override
+  OVERRIDECHECKED=true
+
   rm -rf {{ats_output}} {{banjax_output}} {{bind_output}} 
   if [ "$DEBUG" = true ] ; then
     ansible-playbook {{playbook_dir}}/site.yml -l controller
@@ -511,6 +517,11 @@ function controller_update() {
 }
 
 function awstats_update() {
+  if [ "$OVERRIDECHECKED" = false ]; then
+    check_override
+    OVERRIDECHECKED=true
+  fi
+
   if [ "$DEBUG" = true ] ; then
     ansible-playbook {{playbook_dir}}/site.yml -l awstats
   else
@@ -552,6 +563,17 @@ if [ $exitcode -ne 0 ] ; then
   echo "Something went wrong. Run again in debug mode."
   exit
 fi
+}
+
+function check_override {
+  local check=$(for n in $(grep '^  [a-zA-Z0-9]' override.yml) ; do grep $n clients.yml >> /dev/null || echo "${n%%:} not found in clients.yml. This needs fixed." ; done)
+
+  if [ "$check" == "" ]; then
+    return
+  else
+    echo "$check"
+    exit
+  fi
 }
 
 #########
