removed check that cert files exist before diffing

diff --git a/roles/autobrains_update/templates/autobrains_update.sh.j2 b/roles/autobrains_update/templates/autobrains_update.sh.j2
--- a/roles/autobrains_update/templates/autobrains_update.sh.j2
+++ b/roles/autobrains_update/templates/autobrains_update.sh.j2
@@ -288,20 +288,17 @@ function le_cert_bundle_diff_loop {
       echo -e "Bypassing file $(basename $i)" 
       continue
     fi   
-    if [ -f "$ATS_DIR/conf/ssl/$(basename $i)" ]
+    DIFF_FILES="$ATS_DIR/conf/ssl/$(basename $i) $i"
+    diff -Nq $DIFF_FILES
+    RT=$?
+    if [ $RT -eq 2 ]
     then 
-      DIFF_FILES="$ATS_DIR/conf/ssl/$(basename $i) $i"
-      diff -Nq $DIFF_FILES
-      RT=$?
-      if [ $RT -eq 2 ]
-      then 
-        echo "ERROR: There was something wrong with the diff command"
-      elif [ $RT -eq 1 ]
-      then 
-        yorn "Do you want to install this file in $DNET" "install_file $i $ATS_DIR/conf/ssl/$(basename $i)" 
-        [ "$yn" = 'n' ] || [ "$yn" = 'N' ] && SKIPPED_INSTALL[$DNET]=0 || REMAP_TOUCHED[$DNET]=0
-        echo -e $ECHO_SEPARATOR 
-      fi   
+      echo "ERROR: There was something wrong with the diff command"
+    elif [ $RT -eq 1 ]
+    then 
+      yorn "Do you want to install this file in $DNET" "install_file $i $ATS_DIR/conf/ssl/$(basename $i)" 
+      [ "$yn" = 'n' ] || [ "$yn" = 'N' ] && SKIPPED_INSTALL[$DNET]=0 || REMAP_TOUCHED[$DNET]=0
+      echo -e $ECHO_SEPARATOR 
     fi   
     
 done
