add support for automated LE certs

diff --git a/roles/autobrains_update/templates/autobrains_update.sh.j2 b/roles/autobrains_update/templates/autobrains_update.sh.j2
--- a/roles/autobrains_update/templates/autobrains_update.sh.j2
+++ b/roles/autobrains_update/templates/autobrains_update.sh.j2
@@ -399,6 +399,26 @@ function logs_xml_diff {
   fi
 }
 
+function ssl_multicert_diff {
+  ATS_DIR="{{autobrains_config["deflect_dir"]}}/edges/$DNET{{autobrains_config["trafficserver_dir"]}}"
+  local test=$(match_bypass_file ssl_multicert.config)
+    if [ $test -gt 0 ]; then
+      echo "Bypassing file ssl_multicert.config"
+      return 
+    fi
+  diff -Ntu $ATS_DIR/conf/ssl_multicert.config {{ats_output}}$DNET/ssl_multicert.config
+  RT=$?
+  if [ $RT -eq 2 ]
+  then
+    echo "ERROR: There was something wrong with the diff command"
+  elif [ $RT -eq 1 ]
+  then 
+    yorn "Do you want to install this file" "install_file {{ats_output}}$DNET/ssl_multicert.config $ATS_DIR/conf/ssl_multicert.config" 
+    [ "$yn" = 'n' ] || [ "$yn" = 'N' ] && SKIPPED_INSTALL[$DNET]=0 || REMAP_TOUCHED[$DNET]=0
+    echo -e $ECHO_SEPARATOR
+  fi
+}
+
 function remap_diff {
   ATS_DIR="{{autobrains_config["deflect_dir"]}}/edges/$DNET{{autobrains_config["trafficserver_dir"]}}"
   local test=$(match_bypass_file remap.config)
@@ -463,6 +483,7 @@ for DNET in $DNETS; do
   banjax_new_diff
   banjax_diff_loop
   logs_xml_diff
+  ssl_multicert_diff
   remap_diff
   remap_diff_loop
   cache_diff
