Add function to diff dashboard.timestamp
Signed-off-by: KheOps <kheops@ceops.eu>

diff --git a/roles/autobrains_update/templates/autobrains_update.sh.j2 b/roles/autobrains_update/templates/autobrains_update.sh.j2
--- a/roles/autobrains_update/templates/autobrains_update.sh.j2
+++ b/roles/autobrains_update/templates/autobrains_update.sh.j2
@@ -427,6 +427,26 @@ function logs_xml_diff {
   fi
 }
 
+function dashboard_timestamp_diff {
+  ATS_DIR="{{autobrains_config["deflect_dir"]}}/edges/$DNET{{autobrains_config["trafficserver_dir"]}}"
+  local test=$(match_bypass_file dashboard.timestamp)
+    if [ $test -gt 0 ]; then
+      echo "Bypassing file dashboard.timestamp"
+      return 
+    fi
+  diff -Ntu $ATS_DIR/dashboard.timestamp {{ats_output}}$DNET/dashboard.timestamp
+  RT=$?
+  if [ $RT -eq 2 ]
+  then
+    echo "ERROR: There was something wrong with the diff command"
+  elif [ $RT -eq 1 ]
+  then 
+    yorn "Do you want to install this file" "install_file {{ats_output}}$DNET/dashboard.timestamp $ATS_DIR/dashboard.timestamp" 
+    [ "$yn" = 'n' ] || [ "$yn" = 'N' ] && SKIPPED_INSTALL[$DNET]=0 || REMAP_TOUCHED[$DNET]=0
+    echo -e $ECHO_SEPARATOR
+  fi
+}
+
 function ssl_multicert_diff {
   ATS_DIR="{{autobrains_config["deflect_dir"]}}/edges/$DNET{{autobrains_config["trafficserver_dir"]}}"
   local test=$(match_bypass_file ssl_multicert.config)
