improve dnet separation

diff --git a/roles/autobrains_update/templates/autobrains_update.sh.j2 b/roles/autobrains_update/templates/autobrains_update.sh.j2
--- a/roles/autobrains_update/templates/autobrains_update.sh.j2
+++ b/roles/autobrains_update/templates/autobrains_update.sh.j2
@@ -290,6 +290,35 @@ function remap_diff_loop {
 done 
 }
 
+function le_cert_bundle_diff_loop {
+  ATS_DIR="{{autobrains_config["deflect_dir"]}}/edges/$DNET{{autobrains_config["trafficserver_dir"]}}"
+  for i in {{letsencrypt_output}}/$DNET/*; do
+    ls $i > /dev/null 2>&1
+    RT=$?
+    if [ "$RT" -gt 0 ]; then
+      continue
+    fi
+    local test=$(match_bypass_file "$(basename $i)")
+    if [ $test -gt 0 ]; then 
+      echo -e "Bypassing file $(basename $i)" 
+      continue
+    fi
+    DIFF_FILES="$ATS_DIR/conf/ssl/$(basename $i) $i"
+    diff -q $DIFF_FILES
+    RT=$?
+    if [ $RT -eq 2 ]
+    then
+      echo "ERROR: There was something wrong with the diff command"
+    elif [ $RT -eq 1 ]
+    then
+      yorn "Do you want to install this file" "install_file $i $ATS_DIR/conf/ssl/$(basename $i)" 
+      [ "$yn" = 'n' ] || [ "$yn" = 'N' ] && SKIPPED_INSTALL[$DNET]=0 || REMAP_TOUCHED[$DNET]=0
+      echo -e $ECHO_SEPARATOR 
+  fi
+    
+done 
+}
+
 function banjax_diff_loop {
   ATS_DIR="{{autobrains_config["deflect_dir"]}}/edges/$DNET{{autobrains_config["trafficserver_dir"]}}"
   for i in {{banjax_output}}$DNET/banjax.d/*.bconf; do
@@ -488,6 +517,7 @@ for DNET in $DNETS; do
   remap_diff_loop
   cache_diff
   zone_diff_loop
+  le_cert_bundle_diff_loop
 done
   bind_local_templated_diff
 }
